CREATE TABLE user_details(
   user_id         INTEGER  NOT NULL PRIMARY KEY 
  ,customer_name   VARCHAR(15) NOT NULL
  ,customer_mobile INTEGER  NOT NULL
  ,customer_email  VARCHAR(34) NOT NULL
  ,gender          VARCHAR(6) NOT NULL
  ,City            VARCHAR(9) NOT NULL
  ,State           VARCHAR(11) NOT NULL
  ,Age             INTEGER  NOT NULL
);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (1,'Gokul Kardile',9766044896,'gokulkardile2007@gmail.com','Male','Mumbai','Maharashtra',43);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (2,'ramakrishna kod',9502202203,'ram.kodali@gmail.com','Male','Pune','Maharashtra',51);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (3,'ANKUR NAMDEO',9764000754,'ankurnamdeo@gmail.com','Male','Pune','Maharashtra',49);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (4,'PUSHKAR SINHA',9850964395,'ps2in_hbti@yahoo.com','Male','Pune','Maharashtra',22);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (5,'ARUNAVA MAJUMDA',8087766952,'navamajumdar@gmail.com','Male','Pune','Maharashtra',22);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (6,'vijay mestri',9867019695,'mestri.vijay@gmail.com','Male','Mumbai','Maharashtra',24);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (7,'Tushar Barhate',9422891139,'tushar_barahate@rediffmail.com','Male','Pune','Maharashtra',32);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (8,'amitesh gopal',9960835907,'amiteshgopal@gmail.com','Male','Hyderabad','Telangana',43);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (9,'Aashish Sharma',8097642539,'aashishs29@gmail.com','Male','Hyderabad','Telangana',52);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (10,'RAM BABU',9421058958,'rohanm12805@gmail.com','Male','Hyderabad','Telangana',54);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (11,'SAIKAT MALLIK',9886290641,'saikat.mallik@gmail.com','Male','Hyderabad','Telangana',36);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (12,'SANTOSHKUMAR SI',8108134660,'santoshhsingh@gmail.com','Male','Hyderabad','Telangana',53);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (13,'SHAKIR SHAIKH',9891992568,'shaikh_ss@rediffmail.com','Male','Hyderabad','Telangana',51);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (14,'SHREYAS SHIRGUP',9922273474,'shreyasshirguppe@yahoo.co.in','Male','Hyderabad','Telangana',27);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (15,'SANDEEP KUNJEER',9822015715,'skunjeer@hotmail.com','Male','Hyderabad','Telangana',39);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (16,'Subhash Raybage',9423042311,'subhashraybage@yahoo.com','Female','Hyderabad','Telangana',46);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (17,'SUNNY KAKKAR',9323343676,'sunny_kakkarnai@rediffmail.com','Female','Hyderabad','Telangana',19);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (18,'VINIT KUMAR',9871442088,'vinitkumar.rocky@gmail.com','Female','Hyderabad','Telangana',24);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (19,'ANIL BHARATI',9930806891,'anil.bharati@fermentabiotech.com','Female','Thane','Maharashtra',55);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (20,'ANJAN DATTA',9820572021,'anjan75@rediffmail.com','Female','Mumbai','Maharashtra',30);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (21,'Murtaza Chedawa',9867402326,'mchedawala@hotmail.com','Female','Mumbai','Maharashtra',18);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (22,'Chandrashekaran',9004077910,'ncshekaran@rediffmail.com','Male','Delhi','Delhi',21);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (23,'Antik Kamdar',9833042396,'antik.kamdar@gmail.com','Male','Delhi','Delhi',38);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (24,'VIJAY APTE',9420299821,'aptevijay@rediffmail.com','Male','Delhi','Delhi',21);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (25,'PRAMIL GUPTA',9422516655,'guptapramilinit@yahoo.com','Male','Delhi','Delhi',39);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (26,'Nagaraj Sastry',9223443742,'nag1352@yahoo.com','Male','Delhi','Delhi',51);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (27,'Ravindra Chavan',9223222881,'ravi_chavan28@rediffmail.com','Male','Delhi','Delhi',19);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (28,'nibya mishra',9730446898,'nibyamishra@gmail.com','Male','Delhi','Delhi',17);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (29,'Aamir mumtaz',9022599532,'aamir_mumtaz123@yahoo.com','Male','Delhi','Delhi',45);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (30,'roben skaria',9881445958,'robinskaria@yahoo.com','Male','Delhi','Delhi',23);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (31,'satyendra sahay',9422025256,'sahayfamily@rediffmail.com','Male','Delhi','Delhi',53);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (32,'SANTOSH VISPUTE',9422320463,'santosh.vispute@gmail.com','Male','Delhi','Delhi',48);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (33,'KAMLESH SHAH',9322261160,'shahk53@gmail.com','Male','Delhi','Delhi',27);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (34,'BHAGWAN PANCHAL',9223461136,'shreegurudevgauge@yahoo.com','Male','Delhi','Delhi',16);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (35,'SHIVKUMAR JHA',9822707645,'skjha.1@rediffmail.com','Male','Delhi','Delhi',21);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (36,'stuti sinha',9769181220,'stutisinha6@gmail.com','Female','Delhi','Delhi',22);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (37,'SUNIL SAHNI',9820150435,'sunilsahni@rediffmail.com','Male','Mumbai','Maharashtra',50);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (38,'Vinay Devasthal',9011059275,'vinayvvd@gmail.com','Male','Kolkata','West Bengal',36);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (39,'ARUN ARGADE',9977967483,'arun.argade@gmail.com','Male','Kolkata','West Bengal',53);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (40,'VIJAY KSHIRSAGA',9922435394,'bkvijay159656@gmail.com','Male','Kolkata','West Bengal',37);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (41,'PRAVEEN GUPTA',9867614657,'praveen.gupta@ril.com','Male','Kolkata','West Bengal',22);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (42,'RAHUL JOSHI',9775551729,'rahul8iitkgp@gmail.com','Male','Kolkata','West Bengal',48);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (43,'dhananjay badgu',9421637696,'dbadgujar@rediffmail.com','Male','Kolkata','West Bengal',44);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (44,'MILIND DIGHEKAR',9890957235,'milinddighekar@yahoo.com','Male','Kolkata','West Bengal',23);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (45,'MOHIT PARIHAR',9322967996,'mishuoct@gmail.com','Male','Kolkata','West Bengal',30);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (46,'kokila nandu',9987336688,'mital_gala@yahoo.co.in','Female','Kolkata','West Bengal',26);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (47,'DEVENDRA BAHATK',9765800559,'dbahatkar@yahoo.com','Male','Kolkata','West Bengal',43);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (48,'deepak manjreka',9920066636,'deepak_rm1@rediffmail.com','Male','Kolkata','West Bengal',39);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (49,'DEEPAK SHAH',9820222335,'devdeepak70@yahoo.co.in','Male','Kolkata','West Bengal',17);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (50,'shraddhanand mo',9899259924,'mshraddha2010@gmail.com','Male','Kolkata','West Bengal',53);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (51,'LAXMI DAVE',9819834540,'dave_laxmi@yahoo.co.in','Female','Kolkata','West Bengal',16);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (52,'Deepen Doshi',9867692893,'deepen61@sify.com','Male','Kolkata','West Bengal',32);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (53,'Rishi Mehra',9820504020,'mehrarishi@hotmail.com','Male','Kolkata','West Bengal',31);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (54,'Ronak Vora Vora',9322526800,'deepakvora70@hotmail.com','Male','Kolkata','West Bengal',31);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (55,'MNAOJ SAWANT',9820004653,'manoj_sawant77@yahoo.com','Male','Kolkata','West Bengal',46);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (56,'VARADARAJAN SUB',9766618558,'esjai@eth.net','Male','Kolkata','West Bengal',51);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (57,'HIMANSHU MISHRA',9820708481,'mishra.himanshu12@gmail.com','Male','Kolkata','West Bengal',51);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (58,'Pradnya Dhage',9735371572,'dhage.pradnya@gmail.com','Female','Kolkata','West Bengal',22);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (59,'ravi shankar',8097711605,'colravishankar@hotmail.com','Male','Kolkata','West Bengal',18);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (60,'pankaj jain',9423583251,'dbjewellers@yahoo.com','Male','Kolkata','West Bengal',17);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (61,'DEEPAK BHATIA',9650887833,'dbhatia27@gmail.com','Male','Kolkata','West Bengal',25);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (62,'sham sonar',9890404334,'contactsham@rediffmail.com','Male','Kolkata','West Bengal',17);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (63,'AVINASH KOTHARI',9920624927,'dak_29@hotmail.com','Male','Mumbai','Maharashtra',31);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (64,'mehmoob chauhan',9324090990,'daimand159@yahoo.co.in','Male','Mumbai','Maharashtra',40);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (65,'Kanchan Daswani',9326578718,'daswani.kanchan@gmail.com','Female','Pune','Maharashtra',38);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (66,'krishnadas nair',9821249235,'dasnair@hotmail.com','Male','Mumbai','Maharashtra',20);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (67,'Yogesh Gadgil',9881472724,'coolgyogeshji@gmail.com','Male','Pune','Maharashtra',22);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (68,'daniel tauro',9677139874,'danbryan22@gmail.com','Male','Thane','Maharashtra',49);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (69,'MAYUR MEHTA',8905666066,'coolguy312@hotmail.com','Male','Thane','Maharashtra',15);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (70,'dinkar attarde',9819409536,'dattarde@yahoo.com','Male','dombivli','Maharashtra',29);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (71,'vijay kumar',9820014715,'contactvjay@gmail.com','Male','Thane','Maharashtra',55);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (72,'CHETAN CHINTALW',9922901622,'ctchintalwar@yahoo.com','Male','Jaipur','Rajasthan',40);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (73,'Umang Srivastav',9860479379,'erumangsrivastavas@gmail.com','Male','Jaipur','Rajasthan',40);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (74,'Harmeet Singh',9822648266,'harmeetz@gmail.com','Male','Jaipur','Rajasthan',28);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (75,'mahesh Deshpand',9673338041,'deshpandemaheshp@gmail.com','Male','Jaipur','Rajasthan',43);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (76,'Rubecca Hasan',9021429329,'coolgirl_revs@yahoo.co.in','Female','Jaipur','Rajasthan',42);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (77,'chandrashekhar',9769204448,'chgaushal@gmail.com','Male','Jaipur','Rajasthan',19);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (78,'MONISH DAS',9702542398,'monish_recd@yahoo.com','Male','Jaipur','Rajasthan',20);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (79,'Abdul Taiyeb Ra',9978842071,'abbu_ytl@hotmail.com','Male','Jaipur','Rajasthan',45);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (80,'Rohit Wakde',9960228769,'rohit.wakde@gmail.com','Male','Jaipur','Rajasthan',54);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (81,'SAJAL SAHA',9769256395,'sajalsaha@hotmail.com','Male','Jaipur','Rajasthan',27);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (82,'santosh suryawa',9981240422,'santro6064@yahoo.com','Male','Jaipur','Rajasthan',32);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (83,'shailendra kuma',9918403516,'shailendra_kumar007@rediffmail.com','Male','Jaipur','Rajasthan',43);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (84,'SHRIKANT CHAUDH',9820933899,'shrikant.chaudhari@gmail.com','Male','Jaipur','Rajasthan',26);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (85,'SATISH MARATHE',9890715428,'smarathe@sancharnet.in','Male','Jaipur','Rajasthan',48);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (86,'birat ghadai',9881827503,'subrat.kumar56@yahoo.in','Male','Jaipur','Rajasthan',45);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (87,'supreet singh',9920011797,'supreetonweb@gmail.com','Male','Jaipur','Rajasthan',43);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (88,'VINOD RANA',9923108386,'vinod_rana2k@rediffmail.com','Male','Pune','Maharashtra',50);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (89,'CHANDAN MOTWANI',9978840554,'cmotwani@hotmail.com','Male','Mumbai','Maharashtra',39);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (90,'ASHOK MOHARANA',9930250143,'ashokmoharana@yahoo.com','Male','Mumbai','Maharashtra',55);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (91,'JITENDER CHAUDH',9867000794,'jitenderchaudhary1@rediffmail.com','Male','Mumbai','Maharashtra',43);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (92,'udaykumar dayan',9869443895,'udaykumar_gupta@yahoo.com','Male','Mumbai','Maharashtra',41);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (93,'UMESH KALANTRI',9930070579,'umeshkalantri@gmail.com','Male','Mumbai','Maharashtra',25);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (94,'UMER PATHAN',9224277469,'umer.pathan@ftindia.com','Male','Mumbai','Maharashtra',39);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (95,'ASHISH RANKA',9967763276,'vardhman_jewellers@yahoo.com','Male','Mumbai','Maharashtra',27);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (96,'Vishwanath Mait',9822281329,'vbmaitri@yahoo.com','Male','Pune','Maharashtra',29);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (97,'MICHAEL MASCARE',9969604866,'ullasmichael@gmail.com','Male','Thane','Maharashtra',20);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (98,'RAJGOPAL TIWADI',9423068871,'tiwadirs@gmail.com','Male','solapur','Maharashtra',49);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (99,'A JAYA PRAKASH',9869282753,'a.jayaprakashan@gmail.com','Male','Mumbai','Maharashtra',44);
INSERT INTO user_details(user_id,customer_name,customer_mobile,customer_email,gender,City,State,Age) VALUES (100,'RAJ BARUAH',9654494005,'rkb_iif@yahoo.com','Male','Mumbai','Maharashtra',54);